fix: only lint and format updated files

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -2,7 +2,7 @@
 require() {
   hash "$@" || exit 127
 }
-require sqlfluff parallel
+require sqlfluff parallel git awk
 if [[ -z "$*" ]]; then
   echo "Usage: "
   echo "$0 <list of files>"
@@ -10,14 +10,19 @@ if [[ -z "$*" ]]; then
 fi
 rm -f lint.out
 declare -i exitcode=0
-declare -a files=("$@")
-parallel sqlfluff fix --dialect sqlite ::: "${files[@]}"
-exitcode=$(("$exitcode" + $?))
-if [[ $exitcode != 0 ]]; then
-  parallel sqlfluff lint --dialect sqlite ::: "${files[@]}" &> lint.out
-  exitcode=$?
+# only lint changed files
+readarray -t changedfiles < <(git status -s "$@" | awk -F ' ' '{print $2}')
+if ((${#changedfiles[@]})); then
+  parallel sqlfluff fix --dialect sqlite ::: "${changedfiles[@]}"
+  exitcode=$(("$exitcode" + $?))
   if [[ $exitcode != 0 ]]; then
-    echo "Errors found. Check lint.out"
+    parallel sqlfluff lint --dialect sqlite ::: "${changedfiles[@]}" &> lint.out
+    exitcode=$?
+    if [[ $exitcode != 0 ]]; then
+      echo "Errors found. Check lint.out"
+    fi
   fi
+else
+  echo "No files updated since."
 fi
 exit "$exitcode"
